// Registro e inicio de sesion
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

// Registrar Solicitud
export const ADD_REQUEST = 'ADD_REQUEST';
export const VALIDATE_REQUEST = 'VALIDATE_REQUEST';
export const GET_REQUEST = 'GET_REQUEST';
export const GET_REQUEST_EVENT = 'GET_REQUEST_EVENT';
export const GET_REQUEST_ONE = 'GET_REQUEST_ONE';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const REQUEST_ERROR = 'REQUEST_ERROR';


// Registrar Espacio
export const ADD_ESPACIO = 'ADD_ESPACIO';
export const VALIDATE_ESPACIO = 'VALIDATE_ESPACIO';
export const GET_ESPACIO = 'GET_ESPACIO';
export const GET_ESPACIO_ONE = 'GET_ESPACIO_ONE';
export const UPDATE_ESPACIO = 'UPDATE_ESPACIO';
export const DELETE_ESPACIO = 'DELETE_ESPACIO';
export const ESPACIO_ERROR = 'ESPACIO_ERROR';

// Registrar Sede
export const ADD_SEDE = 'ADD_SEDE';
export const VALIDATE_SEDE = 'VALIDATE_SEDE';
export const GET_SEDE = 'GET_SEDE';
export const UPDATE_SEDE = 'UPDATE_SEDE';
export const DELETE_SEDE = 'DELETE_SEDE';
export const SEDE_ERROR = 'SEDE_ERROR';

// Registrar Cacracteristica
export const ADD_CARACTERISTICA = 'ADD_CARACTERISTICA';
export const VALIDATE_CARACTERISTICA = 'VALIDATE_CARACTERISTICA';
export const GET_CARACTERISTICA = 'GET_CARACTERISTICA';
export const GET_CARACTERISTICA_ONE = 'GET_CARACTERISTICA_ONE';
export const UPDATE_CARACTERISTICA = 'UPDATE_CARACTERISTICA';
export const DELETE_CARACTERISTICA = 'DELETE_CARACTERISTICA';
export const CARACTERISTICA_ERROR = 'CARACTERISTICA_ERROR';

// Registrar Cacracteristica
export const ADD_PREGUNTA = 'ADD_PREGUNTA';
export const VALIDATE_PREGUNTA = 'VALIDATE_PREGUNTA';
export const GET_PREGUNTA = 'GET_PREGUNTA';
export const GET_PREGUNTA_ONE = 'GET_PREGUNTA_ONE';
export const UPDATE_PREGUNTA = 'UPDATE_PREGUNTA';
export const DELETE_PREGUNTA = 'DELETE_PREGUNTA';
export const PREGUNTA_ERROR = 'PREGUNTA_ERROR';
